/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace-hw_xbox.h"

uint16_t _TRACE_NVNET_MII_READ_DSTATE;
uint16_t _TRACE_NVNET_MII_WRITE_DSTATE;
uint16_t _TRACE_NVNET_REG_READ_DSTATE;
uint16_t _TRACE_NVNET_REG_WRITE_DSTATE;
uint16_t _TRACE_NVNET_IO_READ_DSTATE;
uint16_t _TRACE_NVNET_IO_WRITE_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE;
uint16_t _TRACE_NVNET_RX_OVERSIZED_DSTATE;
uint16_t _TRACE_NVNET_RX_FILTER_DROPPED_DSTATE;
TraceEvent _TRACE_NVNET_MII_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_mii_read",
    .sstate = TRACE_NVNET_MII_READ_ENABLED,
    .dstate = &_TRACE_NVNET_MII_READ_DSTATE 
};
TraceEvent _TRACE_NVNET_MII_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_mii_write",
    .sstate = TRACE_NVNET_MII_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_MII_WRITE_DSTATE 
};
TraceEvent _TRACE_NVNET_REG_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_reg_read",
    .sstate = TRACE_NVNET_REG_READ_ENABLED,
    .dstate = &_TRACE_NVNET_REG_READ_DSTATE 
};
TraceEvent _TRACE_NVNET_REG_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_reg_write",
    .sstate = TRACE_NVNET_REG_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_REG_WRITE_DSTATE 
};
TraceEvent _TRACE_NVNET_IO_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_io_read",
    .sstate = TRACE_NVNET_IO_READ_ENABLED,
    .dstate = &_TRACE_NVNET_IO_READ_DSTATE 
};
TraceEvent _TRACE_NVNET_IO_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_io_write",
    .sstate = TRACE_NVNET_IO_WRITE_ENABLED,
    .dstate = &_TRACE_NVNET_IO_WRITE_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_BCAST_MATCH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_bcast_match",
    .sstate = TRACE_NVNET_RX_FILTER_BCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_BCAST_MATCH_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MATCH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_mcast_match",
    .sstate = TRACE_NVNET_RX_FILTER_MCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_MCAST_MATCH_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_mcast_mismatch",
    .sstate = TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MATCH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_ucast_match",
    .sstate = TRACE_NVNET_RX_FILTER_UCAST_MATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_UCAST_MATCH_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_ucast_mismatch",
    .sstate = TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_OVERSIZED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_oversized",
    .sstate = TRACE_NVNET_RX_OVERSIZED_ENABLED,
    .dstate = &_TRACE_NVNET_RX_OVERSIZED_DSTATE 
};
TraceEvent _TRACE_NVNET_RX_FILTER_DROPPED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "nvnet_rx_filter_dropped",
    .sstate = TRACE_NVNET_RX_FILTER_DROPPED_ENABLED,
    .dstate = &_TRACE_NVNET_RX_FILTER_DROPPED_DSTATE 
};
TraceEvent *hw_xbox_trace_events[] = {
    &_TRACE_NVNET_MII_READ_EVENT,
    &_TRACE_NVNET_MII_WRITE_EVENT,
    &_TRACE_NVNET_REG_READ_EVENT,
    &_TRACE_NVNET_REG_WRITE_EVENT,
    &_TRACE_NVNET_IO_READ_EVENT,
    &_TRACE_NVNET_IO_WRITE_EVENT,
    &_TRACE_NVNET_RX_FILTER_BCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_MCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_MCAST_MISMATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_UCAST_MATCH_EVENT,
    &_TRACE_NVNET_RX_FILTER_UCAST_MISMATCH_EVENT,
    &_TRACE_NVNET_RX_OVERSIZED_EVENT,
    &_TRACE_NVNET_RX_FILTER_DROPPED_EVENT,
  NULL,
};

static void trace_hw_xbox_register_events(void)
{
    trace_event_register_group(hw_xbox_trace_events);
}
trace_init(trace_hw_xbox_register_events)
